// This file contains the categories and their respective image paths for the game.

// example commands used to generate the array values for a category:
//   find . -path '*/src/imgs/Sports_Team_Logos/*' | sed 's/\.\///' | sed "s/^/'/" | sed s/$/\',/ | shuf

export const CATEGORIES = {
  Chinese_Takeout: [
    'src/imgs/Chinese_Takeout/01_Takeout_Box.jpg',
    'src/imgs/Chinese_Takeout/02_Egg_Rolls.jpg',
    'src/imgs/Chinese_Takeout/03_Soy_Sauce_Packet.jpg',
    'src/imgs/Chinese_Takeout/04_General_Tsos_Chicken.webp',
    'src/imgs/Chinese_Takeout/05_Fried_Rice.jpg',
    'src/imgs/Chinese_Takeout/06_Char_Siu_Pork.webp',
    'src/imgs/Chinese_Takeout/07_Scallion_Pancake.jpg',
    'src/imgs/Chinese_Takeout/08_Beef_Chow_Fun.jpg',
    'src/imgs/Chinese_Takeout/09_Wonton_Soup.jpg',
    'src/imgs/Chinese_Takeout/10_Chopsticks.jpeg',
    'src/imgs/Chinese_Takeout/11_Menu.jpg',
    'src/imgs/Chinese_Takeout/12_Fried_Dumplings.jpg',
    'src/imgs/Chinese_Takeout/13_Fortune_Cookies.jpg',
    'src/imgs/Chinese_Takeout/14_Lo_Mein.jpg',
    'src/imgs/Chinese_Takeout/15_Egg_Drop_Soup.jpg',
    'src/imgs/Chinese_Takeout/16_Beef_and_Broccoli.jpg',
    'src/imgs/Chinese_Takeout/17_Crab_Rangoon.jpg',
    'src/imgs/Chinese_Takeout/18_Wok.jpg',
    'src/imgs/Chinese_Takeout/19_Soup_Dumplings.avif',
    'src/imgs/Chinese_Takeout/20_Shrimp_Dumpllings.jpg',
    'src/imgs/Chinese_Takeout/21_Siu-Mai.webp',
    'src/imgs/Chinese_Takeout/22_egg_tart.jpg',
    'src/imgs/Chinese_Takeout/23_BBQ-Pork-Steamed-Buns.jpg',
    'src/imgs/Chinese_Takeout/24_Chinese-radish-cake-9th.jpg',
    'src/imgs/Chinese_Takeout/25_Chicken_Feet.jpg',
    'src/imgs/Chinese_Takeout/26_Shrimp-Spring-Rolls-2-scaled.jpg',
    'src/imgs/Chinese_Takeout/27_shrimp-rice-rolls.jpg',
    'src/imgs/Chinese_Takeout/28_dim-sum-spare-ribs-6.jpg',
    'src/imgs/Chinese_Takeout/29_pinapple-buns.jpeg',
    'src/imgs/Chinese_Takeout/30_Fried_taro_cake.jpg',
    'src/imgs/Chinese_Takeout/31_Lo+mai+gai-11.jpg',
    'src/imgs/Chinese_Takeout/32_Sesame_Balls.jpeg',
    'src/imgs/Chinese_Takeout/33_almond-jello-recipe.jpg',
  ],
  Animals: [
    'src/imgs/Animals/Snake.jpg',
    'src/imgs/Animals/Red Panda.jpg',
    'src/imgs/Animals/Dolphin.jpg',
    'src/imgs/Animals/Sloth.jpg',
    'src/imgs/Animals/Bat.jpg',
    'src/imgs/Animals/Walrus.jpg',
    'src/imgs/Animals/Seagull.jpg',
    'src/imgs/Animals/Giraffe.jpg',
    'src/imgs/Animals/Samoyed.jpg',
    'src/imgs/Animals/Raccoon.jpg',
    'src/imgs/Animals/Rabbit.jpg',
    'src/imgs/Animals/Goose.jpg',
    'src/imgs/Animals/Capybara.jpg',
    'src/imgs/Animals/Penguin.jpeg',
    'src/imgs/Animals/Panther.jpg',
    'src/imgs/Animals/Squirrel.jpg',
    'src/imgs/Animals/Armadillo.jpg',
    'src/imgs/Animals/Koala.jpg',
    'src/imgs/Animals/Scorpion.jpg',
    'src/imgs/Animals/Grasshopper.jpg',
    'src/imgs/Animals/Elephant.jpg',
    'src/imgs/Animals/Hippo.jpeg',
    'src/imgs/Animals/Ant.jpg',
    'src/imgs/Animals/Shiba_Inu.jpg',
    'src/imgs/Animals/Pig.jpg',
    'src/imgs/Animals/Horse.jpg',
    'src/imgs/Animals/Quokka.jpg',
    'src/imgs/Animals/Chameleon.jpg',
    'src/imgs/Animals/Komodo_Dragon.jpg',
    'src/imgs/Animals/Tiger.jpg',
    'src/imgs/Animals/Zebra.jpg',
    'src/imgs/Animals/Gorilla.jpg',
    'src/imgs/Animals/Wildebeest.jpg',
    'src/imgs/Animals/Eagle.jpg',
    'src/imgs/Animals/Frog.jpg',
    'src/imgs/Animals/Porcupine.jpg',
    'src/imgs/Animals/Turkey.jpg',
    'src/imgs/Animals/Parrot.jpg',
    'src/imgs/Animals/Spider.jpg',
    'src/imgs/Animals/Jellyfish.jpg',
    'src/imgs/Animals/Cheetah.jpg',
    'src/imgs/Animals/Guinea_Pig.jpg',
    'src/imgs/Animals/Panda.jpg',
    'src/imgs/Animals/Moose.jpg',
    'src/imgs/Animals/Otter.jpg',
    'src/imgs/Animals/Lemur.jpg',
    'src/imgs/Animals/Killer_Whale.jpg',
    'src/imgs/Animals/Gazelle.jpg',
    'src/imgs/Animals/Rhino.jpg',
    'src/imgs/Animals/Goat.jpg',
    'src/imgs/Animals/Possum.jpg',
    'src/imgs/Animals/Lion.jpeg',
    'src/imgs/Animals/Shark.jpg',
    'src/imgs/Animals/Chicken.jpg',
    'src/imgs/Animals/Golden_Retreiver.jpeg',
    'src/imgs/Animals/Peacock.jpg',
    'src/imgs/Animals/Platypus.jpg',
    'src/imgs/Animals/Turtle.jpg',
    'src/imgs/Animals/Octopus.jpg',
    'src/imgs/Animals/Polar_Bear.jpg',
    'src/imgs/Animals/Flamingo.jpg',
    'src/imgs/Animals/Cow.jpg',
    'src/imgs/Animals/Camel.jpg',
    'src/imgs/Animals/Owl.jpg',
    'src/imgs/Animals/Butterfly.jpg',
    'src/imgs/Animals/Seal.jpg',
    'src/imgs/Animals/Bee.jpg',
    'src/imgs/Animals/Deer.jpg',
    'src/imgs/Animals/Alpaca.jpg',
  ],
  Iconic_World_Landmarks: [
    'src/imgs/Iconic_World_Landmarks/01_Statue_of_Liberty.avif',
    'src/imgs/Iconic_World_Landmarks/02_Eiffel_Tower.jpg',
    'src/imgs/Iconic_World_Landmarks/03_Taj_Mahal.avif',
    'src/imgs/Iconic_World_Landmarks/04_Colosseum-Rome-Italy.webp',
    'src/imgs/Iconic_World_Landmarks/05_White-House-Washington-DC.webp',
    'src/imgs/Iconic_World_Landmarks/06_Sydney-Opera-House-Port-Jackson.webp',
    'src/imgs/Iconic_World_Landmarks/07_Big_Ben.jpg',
    'src/imgs/Iconic_World_Landmarks/08_Leaning-Tower-of-Pisa-Italy.webp',
    'src/imgs/Iconic_World_Landmarks/09_Pyramids_at_Giza.jpg',
    'src/imgs/Iconic_World_Landmarks/10_Stonehenge.jpg',
    'src/imgs/Iconic_World_Landmarks/11_Mount_Rushmore.png',
    'src/imgs/Iconic_World_Landmarks/12_Golden_Gate_Bridge.jpg',
    'src/imgs/Iconic_World_Landmarks/13_Machu_Picchu.jpg',
    'src/imgs/Iconic_World_Landmarks/14_Empire_State_Building.jpg',
    'src/imgs/Iconic_World_Landmarks/15_Trevi_Fountain.avif',
    'src/imgs/Iconic_World_Landmarks/16_Grand_Canyon.jpg',
    'src/imgs/Iconic_World_Landmarks/17_Christ_the_Redeemer.jpg',
    'src/imgs/Iconic_World_Landmarks/18_Uluru_or_Ayers_Rock .jpg',
    'src/imgs/Iconic_World_Landmarks/19_Moai_Statues_Easter_Island.jpg',
    'src/imgs/Iconic_World_Landmarks/20_Victoria_Falls.webp',
    'src/imgs/Iconic_World_Landmarks/21_St_Peters_Basilica.avif',
    'src/imgs/Iconic_World_Landmarks/22_Sagrada_Familia.jpg',
    'src/imgs/Iconic_World_Landmarks/23_Great_Wall_of_China.jpg',
    'src/imgs/Iconic_World_Landmarks/24_Arc_de_Triomphe.webp',
    'src/imgs/Iconic_World_Landmarks/25_Little_Mermaid_Denmark.webp',
    'src/imgs/Iconic_World_Landmarks/26_The_Forbidden_City.webp',
    'src/imgs/Iconic_World_Landmarks/27_Louvre_Museum.webp',
    'src/imgs/Iconic_World_Landmarks/28_Mt_Fuji_Japan.webp',
    'src/imgs/Iconic_World_Landmarks/29_Petra_Jordan.jpg',
    'src/imgs/Iconic_World_Landmarks/30_Terracotta_Warriors.jpg',
    'src/imgs/Iconic_World_Landmarks/31_Wailing_Wall.jpg',
    'src/imgs/Iconic_World_Landmarks/32_Mecca.jpg',
    'src/imgs/Iconic_World_Landmarks/33_Taipei_101.webp',
    'src/imgs/Iconic_World_Landmarks/34_Burj_Khalifa.webp',
    'src/imgs/Iconic_World_Landmarks/35_Parthenon-Athens.webp',
  ],
  Animated_Characters: [
    'src/imgs/Animated_Characters/aang.jpg',
    'src/imgs/Animated_Characters/batman.jpg',
    'src/imgs/Animated_Characters/bugs_bunny.jpg',
    'src/imgs/Animated_Characters/buzzlight_year.jpg',
    'src/imgs/Animated_Characters/charlie_brown.jpg',
    'src/imgs/Animated_Characters/courage_the_cowardly_dog.jpg',
    'src/imgs/Animated_Characters/dora_the_explorer.jpg',
    'src/imgs/Animated_Characters/fred_flinstone.jpg',
    'src/imgs/Animated_Characters/garfield.jpg',
    'src/imgs/Animated_Characters/goku.jpg',
    'src/imgs/Animated_Characters/goofy.jpg',
    'src/imgs/Animated_Characters/hinata_shoyo.jpg',
    'src/imgs/Animated_Characters/jimmy_neutron.jpg',
    'src/imgs/Animated_Characters/johnny_bravo.jpg',
    'src/imgs/Animated_Characters/kuroko_tetsuya.jpg',
    'src/imgs/Animated_Characters/levi.jpg',
    'src/imgs/Animated_Characters/luffy.jpg',
    'src/imgs/Animated_Characters/minato.jpg',
    'src/imgs/Animated_Characters/mulan.jpg',
    'src/imgs/Animated_Characters/naruto.jpg',
    'src/imgs/Animated_Characters/omni_man.jpg',
    'src/imgs/Animated_Characters/pink_panther.jpg',
    'src/imgs/Animated_Characters/popeye.jpg',
    'src/imgs/Animated_Characters/snoopy.jpg',
    'src/imgs/Animated_Characters/sonic.jpg',
    'src/imgs/Animated_Characters/spongebob.jpg',
    'src/imgs/Animated_Characters/superman.jpg',
    'src/imgs/Animated_Characters/tanjiro.jpg',
    'src/imgs/Animated_Characters/tarazan.jpg',
    'src/imgs/Animated_Characters/timmy_turner.jpg',
    'src/imgs/Animated_Characters/winnie_the_pooh.jpg',
    'src/imgs/Animated_Characters/zuko.jpg',
    'src/imgs/Animated_Characters/Danny_Phantom.jpg',
    'src/imgs/Animated_Characters/Homer_simpson.jpg',
    'src/imgs/Animated_Characters/Mickey_Mouse.jpg',
  ],
  Sports_Team_Logos: [
    'src/imgs/Sports_Team_Logos/NHL_Philadelphia Flyers.png',
    'src/imgs/Sports_Team_Logos/MLB_Milwaukee Brewers.png',
    'src/imgs/Sports_Team_Logos/NBA_Denver Nuggets.png',
    'src/imgs/Sports_Team_Logos/NBA_Sacramento Kings.png',
    'src/imgs/Sports_Team_Logos/NBA_Chicago Bulls.png',
    'src/imgs/Sports_Team_Logos/NFL_Cincinnati Bengals.png',
    'src/imgs/Sports_Team_Logos/MLB_Houston Astros.png',
    'src/imgs/Sports_Team_Logos/MLB_Philadelphia Phillies.png',
    'src/imgs/Sports_Team_Logos/NHL_Detroit Red Wings.png',
    'src/imgs/Sports_Team_Logos/NBA_New Orleans Pelicans.png',
    'src/imgs/Sports_Team_Logos/NHL_St Louis Blues.png',
    'src/imgs/Sports_Team_Logos/NFL_Indianapolis Colts.png',
    'src/imgs/Sports_Team_Logos/NBA_Miami Heat.png',
    'src/imgs/Sports_Team_Logos/NHL_Boston Bruins.png',
    'src/imgs/Sports_Team_Logos/NHL_Tampa Bay Lightning.png',
    'src/imgs/Sports_Team_Logos/NFL_New England Patriots.png',
    'src/imgs/Sports_Team_Logos/NFL_Minnesota Vikings.png',
    'src/imgs/Sports_Team_Logos/MLB_Boston Red Sox.png',
    'src/imgs/Sports_Team_Logos/NHL_New Jersey Devils.png',
    'src/imgs/Sports_Team_Logos/NFL_Jacksonville Jaguars.png',
    'src/imgs/Sports_Team_Logos/NBA_Brooklyn Nets.png',
    'src/imgs/Sports_Team_Logos/MLB_Toronto Blue Jays.png',
    'src/imgs/Sports_Team_Logos/MLB_Tampa Bay Rays.png',
    'src/imgs/Sports_Team_Logos/NFL_Atlanta Falcons.png',
    'src/imgs/Sports_Team_Logos/MLB_San Francisco Giants.png',
    'src/imgs/Sports_Team_Logos/NFL_New York Jets.png',
    'src/imgs/Sports_Team_Logos/NFL_Chicago Bears.png',
    'src/imgs/Sports_Team_Logos/MLB_St Louis Cardinals.png',
    'src/imgs/Sports_Team_Logos/NFL_Los Angeles Chargers.png',
    'src/imgs/Sports_Team_Logos/MLB_New York Yankees.png',
    'src/imgs/Sports_Team_Logos/NHL_Vancouver Canucks.png',
    'src/imgs/Sports_Team_Logos/NBA_Phoenix Suns.png',
    'src/imgs/Sports_Team_Logos/NFL_Houston Texans.png',
    'src/imgs/Sports_Team_Logos/MLB_Minnesota Twins.png',
    'src/imgs/Sports_Team_Logos/NHL_Pittsburgh Penguins.png',
    'src/imgs/Sports_Team_Logos/NFL_New Orleans Saints.png',
    'src/imgs/Sports_Team_Logos/NFL_Tampa Bay Buccaneers.png',
    'src/imgs/Sports_Team_Logos/NHL_Edmonton Oilers.png',
    'src/imgs/Sports_Team_Logos/NHL_Buffalo Sabres.png',
    'src/imgs/Sports_Team_Logos/NBA_Detroit Pistons.png',
    'src/imgs/Sports_Team_Logos/NFL_Pittsburge Steelers.png',
    'src/imgs/Sports_Team_Logos/NBA_Memphis Grizzlies.png',
    'src/imgs/Sports_Team_Logos/NHL_Tennessee Titans.png',
    'src/imgs/Sports_Team_Logos/MLB_Colorado Rockies.png',
    'src/imgs/Sports_Team_Logos/MLB_Kansas City Royals.png',
    'src/imgs/Sports_Team_Logos/NHL_Carolina Hurricanes.png',
    'src/imgs/Sports_Team_Logos/NBA_Los Angeles Lakers.png',
    'src/imgs/Sports_Team_Logos/NBA_Milwaukee Bucks.png',
    'src/imgs/Sports_Team_Logos/NHL_Columbus Blue Jackets.png',
    'src/imgs/Sports_Team_Logos/MLB_Baltimore Orioles.png',
    'src/imgs/Sports_Team_Logos/NBA_Los Angeles Clippers.png',
    'src/imgs/Sports_Team_Logos/NHL_Ottawa Senators.png',
    'src/imgs/Sports_Team_Logos/NHL_New York Islanders.png',
    'src/imgs/Sports_Team_Logos/MLB_Chicago Cubs.png',
    'src/imgs/Sports_Team_Logos/NFL_Baltimore Ravens.png',
    'src/imgs/Sports_Team_Logos/NFL_Las Vegas Raiders.png',
    'src/imgs/Sports_Team_Logos/NBA_Philadelphia 76ers.png',
    'src/imgs/Sports_Team_Logos/NHL_Vegas Golden Knights.png',
    'src/imgs/Sports_Team_Logos/NBA_Minnesota Timberwolves.png',
    'src/imgs/Sports_Team_Logos/NBA_Utah Jazz.png',
    'src/imgs/Sports_Team_Logos/NHL_Colorado Avalanche.png',
    'src/imgs/Sports_Team_Logos/NHL_Minnesota Wild.png',
    'src/imgs/Sports_Team_Logos/MLB_Athletics.png',
    'src/imgs/Sports_Team_Logos/NBA_New York Knicks.png',
    'src/imgs/Sports_Team_Logos/MLB_Los Angeles Dodgers.png',
    'src/imgs/Sports_Team_Logos/NFL_Buffalo Bills.png',
    'src/imgs/Sports_Team_Logos/NFL_Arizona Cardinals.png',
    'src/imgs/Sports_Team_Logos/NBA_San Antonio Spurs.png',
    'src/imgs/Sports_Team_Logos/NHL_Florida Panthers.png',
    'src/imgs/Sports_Team_Logos/MLB_Chicago White Sox.png',
    'src/imgs/Sports_Team_Logos/NHL_San Jose Sharks.png',
    'src/imgs/Sports_Team_Logos/NHL_Utah Mammoth.png',
    'src/imgs/Sports_Team_Logos/MLB_Pittsburgh Pirates.png',
    'src/imgs/Sports_Team_Logos/NHL_Anaheim Ducks.png',
    'src/imgs/Sports_Team_Logos/MLB_San Diego Padres.png',
    'src/imgs/Sports_Team_Logos/NHL_Chicago Blackhawks.png',
    'src/imgs/Sports_Team_Logos/NBA_Dallas Mavericks.png',
    'src/imgs/Sports_Team_Logos/MLB_Arizona Diamondbacks.png',
    'src/imgs/Sports_Team_Logos/NBA_Houston Rockets.png',
    'src/imgs/Sports_Team_Logos/MLB_Cincinnati Reds.png',
    'src/imgs/Sports_Team_Logos/MLB_Seattle Mariners.jpg',
    'src/imgs/Sports_Team_Logos/NBA_Golden State Warriors.jpg',
    'src/imgs/Sports_Team_Logos/NHL_Winnipeg Jets.png',
    'src/imgs/Sports_Team_Logos/MLB_Los Angeles Angels.png',
    'src/imgs/Sports_Team_Logos/NHL_Calgary Flames.png',
    'src/imgs/Sports_Team_Logos/MLB_Detroit Tigers.png',
    'src/imgs/Sports_Team_Logos/MLB_Miami Marlins.png',
    'src/imgs/Sports_Team_Logos/NBA_Orlando Magic.jpg',
    'src/imgs/Sports_Team_Logos/MLB_Washington Nationals.png',
    'src/imgs/Sports_Team_Logos/NFL_Washington Commanders.png',
    'src/imgs/Sports_Team_Logos/NFL_Los Angeles Rams.png',
    'src/imgs/Sports_Team_Logos/NBA_Indiana Pacers.png',
    'src/imgs/Sports_Team_Logos/MLB_Texas Rangers.png',
    'src/imgs/Sports_Team_Logos/NBA_Oklahoma City Thunder.png',
    'src/imgs/Sports_Team_Logos/NBA_Charlotte Hornets.png',
    'src/imgs/Sports_Team_Logos/NHL_Seattle Kraken.png',
    'src/imgs/Sports_Team_Logos/NBA_Toronto Raptors.png',
    'src/imgs/Sports_Team_Logos/NBA_Washington Wizard.png',
    'src/imgs/Sports_Team_Logos/NFL_Green Bay Packers.png',
    'src/imgs/Sports_Team_Logos/NBA_Boston Celtics.png',
    'src/imgs/Sports_Team_Logos/NFL_Dallas Cowboys.png',
    'src/imgs/Sports_Team_Logos/NFL_Seattle Seahawks.png',
    'src/imgs/Sports_Team_Logos/MLB_New York Mets.png',
    'src/imgs/Sports_Team_Logos/NFL_New York Giants.png',
    'src/imgs/Sports_Team_Logos/NFL_Denver Broncos.png',
    'src/imgs/Sports_Team_Logos/NFL_Miami Dolphins.png',
    'src/imgs/Sports_Team_Logos/NHL_Washington Capitals.png',
    'src/imgs/Sports_Team_Logos/NFL_Carolina Panthers.png',
    'src/imgs/Sports_Team_Logos/NBA_Cleveland Cavaliers.png',
    'src/imgs/Sports_Team_Logos/NBA_Atlanta Hawks.png',
    'src/imgs/Sports_Team_Logos/NHL_Montreal Canadiens.png',
    'src/imgs/Sports_Team_Logos/NFL_Philadelphia Eagles.png',
    'src/imgs/Sports_Team_Logos/NBA_Portland Trailblazers.png',
    'src/imgs/Sports_Team_Logos/MLB_Cleveland Guardians.png',
    'src/imgs/Sports_Team_Logos/NHL_Los Angeles Kings.png',
    'src/imgs/Sports_Team_Logos/MLB_Atlanta Braves.png',
    'src/imgs/Sports_Team_Logos/NFL_Kansas City Chiefs.png',
    'src/imgs/Sports_Team_Logos/NHL_Dallas Stars.png',
    'src/imgs/Sports_Team_Logos/NFL_Cleveland Browns.png',
  ]
} as const;
